require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AfterGraduationsController do

  # This should return the minimal set of attributes required to create a valid
  # AfterGraduation. As you add validations to AfterGraduation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "belong" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AfterGraduationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all after_graduations as @after_graduations" do
      after_graduation = AfterGraduation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:after_graduations).should eq([after_graduation])
    end
  end

  describe "GET show" do
    it "assigns the requested after_graduation as @after_graduation" do
      after_graduation = AfterGraduation.create! valid_attributes
      get :show, {:id => after_graduation.to_param}, valid_session
      assigns(:after_graduation).should eq(after_graduation)
    end
  end

  describe "GET new" do
    it "assigns a new after_graduation as @after_graduation" do
      get :new, {}, valid_session
      assigns(:after_graduation).should be_a_new(AfterGraduation)
    end
  end

  describe "GET edit" do
    it "assigns the requested after_graduation as @after_graduation" do
      after_graduation = AfterGraduation.create! valid_attributes
      get :edit, {:id => after_graduation.to_param}, valid_session
      assigns(:after_graduation).should eq(after_graduation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AfterGraduation" do
        expect {
          post :create, {:after_graduation => valid_attributes}, valid_session
        }.to change(AfterGraduation, :count).by(1)
      end

      it "assigns a newly created after_graduation as @after_graduation" do
        post :create, {:after_graduation => valid_attributes}, valid_session
        assigns(:after_graduation).should be_a(AfterGraduation)
        assigns(:after_graduation).should be_persisted
      end

      it "redirects to the created after_graduation" do
        post :create, {:after_graduation => valid_attributes}, valid_session
        response.should redirect_to(AfterGraduation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved after_graduation as @after_graduation" do
        # Trigger the behavior that occurs when invalid params are submitted
        AfterGraduation.any_instance.stub(:save).and_return(false)
        post :create, {:after_graduation => { "belong" => "invalid value" }}, valid_session
        assigns(:after_graduation).should be_a_new(AfterGraduation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AfterGraduation.any_instance.stub(:save).and_return(false)
        post :create, {:after_graduation => { "belong" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested after_graduation" do
        after_graduation = AfterGraduation.create! valid_attributes
        # Assuming there are no other after_graduations in the database, this
        # specifies that the AfterGraduation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AfterGraduation.any_instance.should_receive(:update).with({ "belong" => "MyString" })
        put :update, {:id => after_graduation.to_param, :after_graduation => { "belong" => "MyString" }}, valid_session
      end

      it "assigns the requested after_graduation as @after_graduation" do
        after_graduation = AfterGraduation.create! valid_attributes
        put :update, {:id => after_graduation.to_param, :after_graduation => valid_attributes}, valid_session
        assigns(:after_graduation).should eq(after_graduation)
      end

      it "redirects to the after_graduation" do
        after_graduation = AfterGraduation.create! valid_attributes
        put :update, {:id => after_graduation.to_param, :after_graduation => valid_attributes}, valid_session
        response.should redirect_to(after_graduation)
      end
    end

    describe "with invalid params" do
      it "assigns the after_graduation as @after_graduation" do
        after_graduation = AfterGraduation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AfterGraduation.any_instance.stub(:save).and_return(false)
        put :update, {:id => after_graduation.to_param, :after_graduation => { "belong" => "invalid value" }}, valid_session
        assigns(:after_graduation).should eq(after_graduation)
      end

      it "re-renders the 'edit' template" do
        after_graduation = AfterGraduation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AfterGraduation.any_instance.stub(:save).and_return(false)
        put :update, {:id => after_graduation.to_param, :after_graduation => { "belong" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested after_graduation" do
      after_graduation = AfterGraduation.create! valid_attributes
      expect {
        delete :destroy, {:id => after_graduation.to_param}, valid_session
      }.to change(AfterGraduation, :count).by(-1)
    end

    it "redirects to the after_graduations list" do
      after_graduation = AfterGraduation.create! valid_attributes
      delete :destroy, {:id => after_graduation.to_param}, valid_session
      response.should redirect_to(after_graduations_url)
    end
  end

end
