require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GuidancesController do

  # This should return the minimal set of attributes required to create a valid
  # Guidance. As you add validations to Guidance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "guidance_date" => "2014-01-07" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GuidancesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all guidances as @guidances" do
      guidance = Guidance.create! valid_attributes
      get :index, {}, valid_session
      assigns(:guidances).should eq([guidance])
    end
  end

  describe "GET show" do
    it "assigns the requested guidance as @guidance" do
      guidance = Guidance.create! valid_attributes
      get :show, {:id => guidance.to_param}, valid_session
      assigns(:guidance).should eq(guidance)
    end
  end

  describe "GET new" do
    it "assigns a new guidance as @guidance" do
      get :new, {}, valid_session
      assigns(:guidance).should be_a_new(Guidance)
    end
  end

  describe "GET edit" do
    it "assigns the requested guidance as @guidance" do
      guidance = Guidance.create! valid_attributes
      get :edit, {:id => guidance.to_param}, valid_session
      assigns(:guidance).should eq(guidance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Guidance" do
        expect {
          post :create, {:guidance => valid_attributes}, valid_session
        }.to change(Guidance, :count).by(1)
      end

      it "assigns a newly created guidance as @guidance" do
        post :create, {:guidance => valid_attributes}, valid_session
        assigns(:guidance).should be_a(Guidance)
        assigns(:guidance).should be_persisted
      end

      it "redirects to the created guidance" do
        post :create, {:guidance => valid_attributes}, valid_session
        response.should redirect_to(Guidance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved guidance as @guidance" do
        # Trigger the behavior that occurs when invalid params are submitted
        Guidance.any_instance.stub(:save).and_return(false)
        post :create, {:guidance => { "guidance_date" => "invalid value" }}, valid_session
        assigns(:guidance).should be_a_new(Guidance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Guidance.any_instance.stub(:save).and_return(false)
        post :create, {:guidance => { "guidance_date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested guidance" do
        guidance = Guidance.create! valid_attributes
        # Assuming there are no other guidances in the database, this
        # specifies that the Guidance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Guidance.any_instance.should_receive(:update).with({ "guidance_date" => "2014-01-07" })
        put :update, {:id => guidance.to_param, :guidance => { "guidance_date" => "2014-01-07" }}, valid_session
      end

      it "assigns the requested guidance as @guidance" do
        guidance = Guidance.create! valid_attributes
        put :update, {:id => guidance.to_param, :guidance => valid_attributes}, valid_session
        assigns(:guidance).should eq(guidance)
      end

      it "redirects to the guidance" do
        guidance = Guidance.create! valid_attributes
        put :update, {:id => guidance.to_param, :guidance => valid_attributes}, valid_session
        response.should redirect_to(guidance)
      end
    end

    describe "with invalid params" do
      it "assigns the guidance as @guidance" do
        guidance = Guidance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Guidance.any_instance.stub(:save).and_return(false)
        put :update, {:id => guidance.to_param, :guidance => { "guidance_date" => "invalid value" }}, valid_session
        assigns(:guidance).should eq(guidance)
      end

      it "re-renders the 'edit' template" do
        guidance = Guidance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Guidance.any_instance.stub(:save).and_return(false)
        put :update, {:id => guidance.to_param, :guidance => { "guidance_date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested guidance" do
      guidance = Guidance.create! valid_attributes
      expect {
        delete :destroy, {:id => guidance.to_param}, valid_session
      }.to change(Guidance, :count).by(-1)
    end

    it "redirects to the guidances list" do
      guidance = Guidance.create! valid_attributes
      delete :destroy, {:id => guidance.to_param}, valid_session
      response.should redirect_to(guidances_url)
    end
  end

end
