require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GuidancesUsersController do

  # This should return the minimal set of attributes required to create a valid
  # GuidancesUser. As you add validations to GuidancesUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GuidancesUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all guidances_users as @guidances_users" do
      guidances_user = GuidancesUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:guidances_users).should eq([guidances_user])
    end
  end

  describe "GET show" do
    it "assigns the requested guidances_user as @guidances_user" do
      guidances_user = GuidancesUser.create! valid_attributes
      get :show, {:id => guidances_user.to_param}, valid_session
      assigns(:guidances_user).should eq(guidances_user)
    end
  end

  describe "GET new" do
    it "assigns a new guidances_user as @guidances_user" do
      get :new, {}, valid_session
      assigns(:guidances_user).should be_a_new(GuidancesUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested guidances_user as @guidances_user" do
      guidances_user = GuidancesUser.create! valid_attributes
      get :edit, {:id => guidances_user.to_param}, valid_session
      assigns(:guidances_user).should eq(guidances_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GuidancesUser" do
        expect {
          post :create, {:guidances_user => valid_attributes}, valid_session
        }.to change(GuidancesUser, :count).by(1)
      end

      it "assigns a newly created guidances_user as @guidances_user" do
        post :create, {:guidances_user => valid_attributes}, valid_session
        assigns(:guidances_user).should be_a(GuidancesUser)
        assigns(:guidances_user).should be_persisted
      end

      it "redirects to the created guidances_user" do
        post :create, {:guidances_user => valid_attributes}, valid_session
        response.should redirect_to(GuidancesUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved guidances_user as @guidances_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        GuidancesUser.any_instance.stub(:save).and_return(false)
        post :create, {:guidances_user => { "user_id" => "invalid value" }}, valid_session
        assigns(:guidances_user).should be_a_new(GuidancesUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GuidancesUser.any_instance.stub(:save).and_return(false)
        post :create, {:guidances_user => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested guidances_user" do
        guidances_user = GuidancesUser.create! valid_attributes
        # Assuming there are no other guidances_users in the database, this
        # specifies that the GuidancesUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GuidancesUser.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => guidances_user.to_param, :guidances_user => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested guidances_user as @guidances_user" do
        guidances_user = GuidancesUser.create! valid_attributes
        put :update, {:id => guidances_user.to_param, :guidances_user => valid_attributes}, valid_session
        assigns(:guidances_user).should eq(guidances_user)
      end

      it "redirects to the guidances_user" do
        guidances_user = GuidancesUser.create! valid_attributes
        put :update, {:id => guidances_user.to_param, :guidances_user => valid_attributes}, valid_session
        response.should redirect_to(guidances_user)
      end
    end

    describe "with invalid params" do
      it "assigns the guidances_user as @guidances_user" do
        guidances_user = GuidancesUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GuidancesUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => guidances_user.to_param, :guidances_user => { "user_id" => "invalid value" }}, valid_session
        assigns(:guidances_user).should eq(guidances_user)
      end

      it "re-renders the 'edit' template" do
        guidances_user = GuidancesUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GuidancesUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => guidances_user.to_param, :guidances_user => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested guidances_user" do
      guidances_user = GuidancesUser.create! valid_attributes
      expect {
        delete :destroy, {:id => guidances_user.to_param}, valid_session
      }.to change(GuidancesUser, :count).by(-1)
    end

    it "redirects to the guidances_users list" do
      guidances_user = GuidancesUser.create! valid_attributes
      delete :destroy, {:id => guidances_user.to_param}, valid_session
      response.should redirect_to(guidances_users_url)
    end
  end

end
